export enum HotkeyEvent {
	FOCUS_ADDRESS_BAR = "FOCUS_ADDRESS_BAR",
	TAB_SWITCHER_FORWARD = "TAB_SWITCHER_FORWARD",
	TAB_SWITCHER_BACKWARD = "TAB_SWITCHER_BACKWARD",
	FIND_IN_PAGE = "FIND_IN_PAGE",
}
